FROM python:3.9-buster as build

RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev

RUN python3 -m pip install grpcio-tools

COPY protos /app/protos
COPY server /app/server
COPY services /app/services

WORKDIR /app
RUN cd protos && chmod +x build.sh && ./build.sh

EXPOSE 7878

# CMD ["PYTHONPATH=.", "python", "server/hello.py"]
CMD ["python", "-m", "server.hello"]
